In [1]:
# 处理缺失数据

In [4]:
import pandas as pd
import numpy as np
string_data = pd.Series(['aardvark','artichoke',np.nan,'avocada'])

In [5]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocada
dtype: object

In [6]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data[0]=None

In [8]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [9]:
from numpy import nan as NA

In [10]:
data = pd.Series([1,NA,3.5,NA,7])

In [11]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data.notnull()

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [13]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [18]:
data=pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])

In [19]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [21]:
data.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [22]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [25]:
data[4]=NA

In [26]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [27]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [28]:
df=pd.DataFrame(np.random.randn(7,3))

In [29]:
df

0         1         2
0  1.282884  0.115687  0.085490
1 -1.220237 -0.718670  1.014738
2  0.364589 -0.773125 -1.041544
3  0.224896  0.376919  1.722356
4  1.525739  1.903656  0.607947
5 -2.030629 -0.151804 -0.695825
6  0.832581  0.973555 -0.180363

In [30]:
df.iloc[0:4,1]=NA
df.iloc[:2,2]=NA

In [31]:
df

0         1         2
0  1.282884       NaN       NaN
1 -1.220237       NaN       NaN
2  0.364589       NaN -1.041544
3  0.224896       NaN  1.722356
4  1.525739  1.903656  0.607947
5 -2.030629 -0.151804 -0.695825
6  0.832581  0.973555 -0.180363

In [32]:
df.dropna()

0         1         2
4  1.525739  1.903656  0.607947
5 -2.030629 -0.151804 -0.695825
6  0.832581  0.973555 -0.180363

In [33]:
df.dropna(thresh=2)

0         1         2
2  0.364589       NaN -1.041544
3  0.224896       NaN  1.722356
4  1.525739  1.903656  0.607947
5 -2.030629 -0.151804 -0.695825
6  0.832581  0.973555 -0.180363

In [34]:
## 填充缺失值

In [35]:
df.fillna(0)

0         1         2
0  1.282884  0.000000  0.000000
1 -1.220237  0.000000  0.000000
2  0.364589  0.000000 -1.041544
3  0.224896  0.000000  1.722356
4  1.525739  1.903656  0.607947
5 -2.030629 -0.151804 -0.695825
6  0.832581  0.973555 -0.180363

In [36]:
df.fillna({1:0.5,2:0})

0         1         2
0  1.282884  0.500000  0.000000
1 -1.220237  0.500000  0.000000
2  0.364589  0.500000 -1.041544
3  0.224896  0.500000  1.722356
4  1.525739  1.903656  0.607947
5 -2.030629 -0.151804 -0.695825
6  0.832581  0.973555 -0.180363

In [39]:
_=df.fillna(0,inplace=True)

In [40]:
df

0         1         2
0  1.282884  0.000000  0.000000
1 -1.220237  0.000000  0.000000
2  0.364589  0.000000 -1.041544
3  0.224896  0.000000  1.722356
4  1.525739  1.903656  0.607947
5 -2.030629 -0.151804 -0.695825
6  0.832581  0.973555 -0.180363

In [41]:
df=pd.DataFrame(np.random.randn(6,3))

In [42]:
df

0         1         2
0 -0.167403  0.596398  1.136251
1  0.156269  0.438106  1.223170
2 -1.034876  0.944720 -0.115100
3 -3.817440  0.241366  0.601944
4  0.283304 -2.147905 -0.583465
5  0.816207  1.149049 -1.264942

In [43]:
df.iloc[2:,1]=NA
df.iloc[4:,2]=NA

In [44]:
df

0         1         2
0 -0.167403  0.596398  1.136251
1  0.156269  0.438106  1.223170
2 -1.034876       NaN -0.115100
3 -3.817440       NaN  0.601944
4  0.283304       NaN       NaN
5  0.816207       NaN       NaN

In [46]:
df.fillna(method='ffill')

0         1         2
0 -0.167403  0.596398  1.136251
1  0.156269  0.438106  1.223170
2 -1.034876  0.438106 -0.115100
3 -3.817440  0.438106  0.601944
4  0.283304  0.438106  0.601944
5  0.816207  0.438106  0.601944

In [47]:
df.fillna(method='ffill',limit=2)

0         1         2
0 -0.167403  0.596398  1.136251
1  0.156269  0.438106  1.223170
2 -1.034876  0.438106 -0.115100
3 -3.817440  0.438106  0.601944
4  0.283304       NaN  0.601944
5  0.816207       NaN  0.601944

In [51]:
data=pd.Series([1,NA,3.5,NA,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [52]:
df.fillna(data.mean())

0         1         2
0 -0.167403  0.596398  1.136251
1  0.156269  0.438106  1.223170
2 -1.034876  3.833333 -0.115100
3 -3.817440  3.833333  0.601944
4  0.283304  3.833333  3.833333
5  0.816207  3.833333  3.833333

In [53]:
## 数据转换

In [54]:
data=pd.DataFrame({'k1':['one','two']*3+['two'],'k2':[1,1,2,3,3,4,4]})

In [55]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [56]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [59]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [60]:
data['v1']=range(7)

In [61]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [62]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [63]:
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [65]:
data.drop_duplicates(['k1','k2'])

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5

In [76]:
data=pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'],
                   'ounces':[4,3,12,6,7.5,8,3,5,6]
                  })

In [77]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [78]:
meat_to_animal={'bacon':'pig','pulled pork':'pig','pastrami':'cow','corned beef':'cow','honey ham':'pig','nova lox':'slamon'}

In [79]:
lowercased=data['food'].str.lower()

In [80]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [81]:
data['animal']=lowercased.map(meat_to_animal)

In [82]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  slamon

In [83]:
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    slamon
Name: food, dtype: object

In [84]:
## 数值替换

In [85]:
data=pd.Series([1., -999., 2., -999., -1000., 3.])

In [86]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [87]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [88]:
data.replace([-999,-1000],NA)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [89]:
data.replace([-999,-1000],[NA,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [90]:
data.replace({-999:NA,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [91]:
# 重命名轴索引

In [92]:
data=pd.DataFrame(np.arange(12).reshape(3,4),index=['Ohio','Colorado','New York'],columns=['one','two','three','four'])

In [93]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [103]:
transform=lambda x:x[:4].upper()

In [102]:
data.index.map(transform)

Index(['OHIO', 'COLORADO', 'NEW YORK'], dtype='object')

In [105]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [106]:
data.index=data.index.map(transform)

In [107]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [108]:
data=pd.DataFrame(np.arange(12).reshape(3,4),index=['Ohio','Colorado','New York'],columns=['one','two','three','four'])

In [109]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [110]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [113]:
data.rename(index={'Ohio':'INDIANA'},columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

In [114]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [117]:
data.rename(index={'Ohio':'INDIANA'},inplace=True)

In [118]:
data

one  two  three  four
INDIANA     0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [119]:
# 离散化和面元划分

In [120]:
ages=[20,22,25,27,21,23,37,31,61,45,41,32]

In [122]:
ages

[20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [123]:
bins=[18,25,35,60,100]

In [124]:
cats=pd.cut(ages,bins)

In [127]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [128]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [130]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [131]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [132]:
pd.cut(ages,bins,right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [133]:
pd.cut(ages,bins,right=True)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [134]:
group_names=['Youth','YoungAdult','MiddleAges','Senior']

In [135]:
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAges, MiddleAges, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAges < Senior]

In [136]:
data=np.random.rand(20)

In [137]:
data

array([0.61543638, 0.48667371, 0.05014657, 0.22076505, 0.77246983,
       0.1401785 , 0.87288884, 0.71349632, 0.61489151, 0.09647252,
       0.43033807, 0.47870536, 0.30706651, 0.72248439, 0.44963139,
       0.15435947, 0.03373677, 0.11796816, 0.90505068, 0.76172085])

In [138]:
pd.cut(data,4)

[(0.469, 0.687], (0.469, 0.687], (0.0329, 0.252], (0.0329, 0.252], (0.687, 0.905], ..., (0.0329, 0.252], (0.0329, 0.252], (0.0329, 0.252], (0.687, 0.905], (0.687, 0.905]]
Length: 20
Categories (4, interval[float64]): [(0.0329, 0.252] < (0.252, 0.469] < (0.469, 0.687] < (0.687, 0.905]]

In [139]:
pd.cut(data, 4, precision=2)

[(0.47, 0.69], (0.47, 0.69], (0.033, 0.25], (0.033, 0.25], (0.69, 0.91], ..., (0.033, 0.25], (0.033, 0.25], (0.033, 0.25], (0.69, 0.91], (0.69, 0.91]]
Length: 20
Categories (4, interval[float64]): [(0.033, 0.25] < (0.25, 0.47] < (0.47, 0.69] < (0.69, 0.91]]

In [141]:
data=np.random.rand(1000)

In [142]:
data

array([5.41099745e-01, 8.70716239e-01, 2.60004577e-01, 8.53352291e-02,
       4.64924729e-01, 4.62802035e-01, 8.42422781e-01, 4.92508252e-01,
       3.42263724e-01, 9.79229814e-01, 8.31224372e-01, 7.27194813e-01,
       1.04167140e-02, 6.13156663e-02, 8.17344786e-01, 9.35045308e-02,
       8.05481599e-01, 2.29842486e-01, 6.20419563e-01, 9.94229918e-01,
       7.41604493e-01, 3.11884509e-02, 8.60661364e-01, 1.61281056e-01,
       2.02901047e-01, 8.46115802e-03, 3.39866912e-01, 3.44390631e-01,
       8.18215387e-01, 8.66710071e-01, 2.95990528e-01, 3.08105563e-02,
       6.06212482e-01, 6.16426880e-03, 4.51666724e-01, 4.82471265e-01,
       9.80559908e-01, 2.81018012e-01, 4.59407826e-01, 2.34034347e-01,
       1.54680722e-01, 9.42120474e-01, 1.69884497e-01, 2.24024606e-01,
       5.91441616e-01, 4.31308539e-01, 4.62232688e-02, 2.61431275e-02,
       3.13824693e-01, 3.28058137e-01, 4.78990309e-01, 3.02217341e-01,
       7.26160207e-01, 1.96326630e-01, 3.21142537e-01, 8.14934477e-01,
      

In [143]:
cats=pd.qcut(data,4)

In [144]:
cats

[(0.502, 0.751], (0.751, 0.999], (0.257, 0.502], (-0.000539, 0.257], (0.257, 0.502], ..., (0.502, 0.751], (0.751, 0.999], (0.502, 0.751], (-0.000539, 0.257], (0.751, 0.999]]
Length: 1000
Categories (4, interval[float64]): [(-0.000539, 0.257] < (0.257, 0.502] < (0.502, 0.751] < (0.751, 0.999]]

In [146]:
pd.value_counts(cats)

(0.751, 0.999]        250
(0.502, 0.751]        250
(0.257, 0.502]        250
(-0.000539, 0.257]    250
dtype: int64

In [147]:
#检测和过滤异常值

In [148]:
data=pd.DataFrame(np.random.randn(1000,4))

In [150]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.066178    -0.018765     0.039902     0.033039
std       0.982400     1.016475     1.025453     1.001763
min      -3.766760    -3.225787    -3.428037    -3.313506
25%      -0.711691    -0.694632    -0.689722    -0.669563
50%      -0.050084    -0.007581     0.075120     0.037438
75%       0.588299     0.689946     0.735537     0.699894
max       2.974599     3.830850     3.458916     3.149576

In [158]:
col=data[2]

In [160]:
col[np.abs(col) > 3]

556    3.247392
557   -3.428037
645    3.458916
Name: 2, dtype: float64

In [162]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
250 -3.304330 -0.261038  0.162536 -0.479579
417 -3.766760  0.595899  0.954695 -2.121806
496 -0.910425  0.778273 -0.082051  3.149576
556 -0.507565  0.762680  3.247392 -1.417587
557 -0.494791 -0.050197 -3.428037  0.789963
583  0.611009 -3.225787 -0.031348 -0.183738
585 -0.760633  0.789589  1.331846 -3.313506
645 -0.168570  0.176842  3.458916 -0.443774
907 -0.801113  3.830850  0.668772  0.170583

In [163]:
data[np.abs(data) > 3]=np.sign(data)*3

In [164]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.065107    -0.019370     0.039624     0.033203
std       0.978844     1.012971     1.021913     1.000308
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.711691    -0.694632    -0.689722    -0.669563
50%      -0.050084    -0.007581     0.075120     0.037438
75%       0.588299     0.689946     0.735537     0.699894
max       2.974599     3.000000     3.000000     3.000000

In [165]:
# 排列和随机采样

In [166]:
df = pd.DataFrame(np.arange(5*4).reshape(5,4))

In [167]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [168]:
sampler=np.random.permutation(5)

In [169]:
sampler

array([4, 3, 2, 0, 1])

In [170]:
df[3]

0     3
1     7
2    11
3    15
4    19
Name: 3, dtype: int32

In [180]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7

In [182]:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
0   0   1   2   3
4  16  17  18  19

In [183]:
choice=pd.Series([5,7,-1,6,4])

In [189]:
choice.sample(n=10,replace=True)

1    7
1    7
2   -1
3    6
2   -1
4    4
2   -1
0    5
0    5
1    7
dtype: int64

In [190]:
# 计算指标 /哑变量

In [191]:
###字符串操作

In [206]:
val='a,b, guido'

In [207]:
val.split(',')

['a', 'b', ' guido']

In [208]:
pieces=[x.strip() for x in val.split(',')]

In [209]:
pieces

['a', 'b', 'guido']

In [210]:
first, second, third = pieces

In [211]:
first+'::'+second+'::'+third

'a::b::guido'

In [212]:
'::'.join(pieces)

'a::b::guido'

In [213]:
val.index(',')

1

In [214]:
val.find(':')

-1

In [215]:
val.replace(',',':')

'a:b: guido'

In [219]:
val.count(',')

2

In [220]:
val

'a,b, guido'

In [ ]:
# 